export const permissionsList = {
  product: {
    GET_PRODUCTS: 'GET_PRODUCTS',
    CREATE_PRODUCTS: 'CREATE_PRODUCTS',
    UPDATE_PRODUCTS: 'UPDATE_PRODUCTS',
    DELETE_PRODUCTS: 'DELETE_PRODUCTS',
  },
};
