apiVersion: v1
kind: Pod
metadata:
  name: mail-pod
  labels:
    name: mail-pod
    app: nestjs-microservices
spec:
  containers:
    - name: mail
      image: dmutre/microservice-api-mail
      env:
        - name: QUEUE_NAME
          value: mail_queue
        - name: RMQ_URL
          value: amqp://rabbitmq-service:5672
        - name: FRONTEND_URL
          value: http://localhost:3006
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              key: SMTP_HOST
              name: nestjs-microservices
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              key: SMTP_USERNAME
              name: nestjs-microservices
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SMTP_PASSWORD
              name: nestjs-microservices