apiVersion: v1
kind: Pod
metadata:
  namespace: nestjs-microservices
  name: postgres-pod
  labels:
    name: postgres-pod
    app: nestjs-microservice
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: postgres-pvc
          mountPath: /var/lib/postgresql/data
        - name: initdb-script
          mountPath: /docker-entrypoint-initdb.d/init-db.sh
          subPath: init-db.sh
      env:
       - name: POSTGRES_USER
         valueFrom:
           secretKeyRef:
             name: nestjs-microservices
             key: POSTGRES_USER
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
             name: nestjs-microservices
             key: POSTGRES_PASSWORD
  volumes:
  - name: postgres-pvc
    persistentVolumeClaim:
      claimName: postgres-pvc
  - name: initdb-script
    configMap:
      name: postgres-initdb
